language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
  - export DJANGO_SETTINGS_MODULE=style_guide.test_settings
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
script:
  - make test
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4
branches:
  only:
    - develop
