language: python
python:
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
install:
  - pip install -e .
  - pip install -r requirements/development.txt Django==$DJANGO
script:
  - `which nosetests` --with-noy
env:
  - DJANGO=1.4
